<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-04-03T23:56:37 IST" name="Suite" finished-at="2025-04-03T23:57:15 IST" duration-ms="37180">
    <groups>
      <group name="smoke">
        <method signature="AmountCaluculationValidation.amountCalculation(java.util.HashMap)[pri:0, instance:org.ankurgoyal.AmountCaluculationValidation@c05fddc]" name="amountCalculation" class="org.ankurgoyal.AmountCaluculationValidation"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2025-04-03T23:56:37 IST" name="Test" finished-at="2025-04-03T23:57:15 IST" duration-ms="37180">
      <class name="org.ankurgoyal.AmountCaluculationValidation">
        <test-method is-config="true" signature="appiumServerStart()[pri:0, instance:org.ankurgoyal.AmountCaluculationValidation@c05fddc]" started-at="2025-04-03T23:56:37 IST" name="appiumServerStart" finished-at="2025-04-03T23:56:45 IST" duration-ms="7265" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- appiumServerStart -->
        <test-method is-config="true" signature="preSetup()[pri:0, instance:org.ankurgoyal.AmountCaluculationValidation@c05fddc]" started-at="2025-04-03T23:56:45 IST" name="preSetup" finished-at="2025-04-03T23:56:45 IST" duration-ms="112" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preSetup -->
        <test-method signature="amountCalculation(java.util.HashMap)[pri:0, instance:org.ankurgoyal.AmountCaluculationValidation@c05fddc]" started-at="2025-04-03T23:56:45 IST" name="amountCalculation" data-provider="getData" finished-at="2025-04-03T23:57:00 IST" duration-ms="14860" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{name=Ankur Goyal, country=Argentina, gender=male}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [280.97] but found [281.97]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [280.97] but found [281.97]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEquals(Assert.java:728)
at org.testng.Assert.assertEquals(Assert.java:775)
at org.ankurgoyal.AmountCaluculationValidation.amountCalculation(AmountCaluculationValidation.java:57)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- amountCalculation -->
        <test-method is-config="true" signature="preSetup()[pri:0, instance:org.ankurgoyal.AmountCaluculationValidation@c05fddc]" started-at="2025-04-03T23:57:01 IST" name="preSetup" finished-at="2025-04-03T23:57:01 IST" duration-ms="116" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preSetup -->
        <test-method signature="amountCalculation(java.util.HashMap)[pri:0, instance:org.ankurgoyal.AmountCaluculationValidation@c05fddc]" started-at="2025-04-03T23:57:01 IST" name="amountCalculation" data-provider="getData" finished-at="2025-04-03T23:57:14 IST" duration-ms="12957" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{name=Anushka Goyal, country=Albania, gender=female}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [280.97] but found [281.97]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [280.97] but found [281.97]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEquals(Assert.java:728)
at org.testng.Assert.assertEquals(Assert.java:775)
at org.ankurgoyal.AmountCaluculationValidation.amountCalculation(AmountCaluculationValidation.java:57)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- amountCalculation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:org.ankurgoyal.AmountCaluculationValidation@c05fddc]" started-at="2025-04-03T23:57:14 IST" name="tearDown" finished-at="2025-04-03T23:57:15 IST" duration-ms="360" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- org.ankurgoyal.AmountCaluculationValidation -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
